GET https://bun-imap-rest-api.gerold-penz.at/api/mailboxes/
X-Imap-Host: {{IMAP_HOST}}
X-Imap-Port: {{IMAP_PORT}}
X-Imap-Tls: {{IMAP_TLS}}
X-Imap-User: {{IMAP_USER}}
X-Imap-Password: {{IMAP_PASSWORD}}
